apiVersion: v1
kind: Pod
metadata:
  name: workspace-pod-negative-1
  labels:
    workspace-id: ws111222
spec:
  volumes:
  - name: private-vol
    hostPath:
      path: "/mnt/workspace/private/test"
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: private-vol
      mountPath: "/data/private"
