apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-workspace-volumes
spec:
  validationFailureAction: enforce
  rules:
  - name: remove-public-workspace-vols
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            workspace-id: ws111222
    mutate:
      patchStrategicMerge:
        spec:
          volumes:
          - name: public-vol
            hostPath:
              path: /mnt/workspace/public/test
            $patch: delete
          containers:
          - name: test-container
            volumeMounts:
            - name: public-vol
              mountPath: /data/public
              $patch: delete
